name: places
description: "proyecto"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

  assets:
    - assets/images/persona1.jpg
    - assets/images/persona2.jpg
    - assets/images/persona3.jpg
    - assets/images/persona4.jpg
    - assets/images/persona5.jpg
    - assets/images/lugar.jpg
    - assets/images/lugar2.jpg
    - assets/images/lugar3.jpg
    - assets/images/lugar4.jpg
    - assets/images/lugar5.jpg
    - assets/images/lugar6.jpg
